### ISSUE TITLE
Use-case for Vetted.lock

### ISSUE THREAD

**Issue by bholley** [bholley/cargo-vet#13]
@Gankra what did you have in mind? I'm not sure the tool will ever need it, and users will generally have the last working version checked into VCS.

**Comment by Gankra** [comment]
I think this is basically the consequence of me being fuzzy about what certain commands like suggest/diff/vet are "comparing against" in #9.

Like we want to compare a "current (new)" copy to an "old (audited)" copy, and it's not 100% obvious to me what the right choices are for those. You've made a solid argument for current="whatever the current Cargo.lock is", but what about old? I think there are two answers:

1. The last vetted version (Vetted.lock) ("what has changed since last you vetted")
2. The largest audited/allowed version <= current ("the minimum review to do to get compliant")

Forcing myself to write this down has made it pretty clear in my mind that I think you always want 2, but there's something nagging at the back of my mind that 1 is sometimes a useful notion to have around?

**Comment by Gankra** [comment]
I guess one detail is whether it's a useful notion to distinguish between "this is a repo that vet happens to successfully run on" and "this is a repo that has been explicitly vetted and the result checked in". I think that distinction is partially captured by just using `--locked` in CI..?

**Comment by bholley** [comment]
> 



> I think this is basically the consequence of me being fuzzy about what certain commands like suggest/diff/vet are "comparing against" in #9.
> 
> Like we want to compare a "current (new)" copy to an "old (audited)" copy

In my mental model there's not really an "old" state. The core job of cargo vet is to tell me whether my current dependencies are all covered by audits, and if not, identify the minimal amount of work to get there. In the case where `cargo vet` was previously passing, I pulled in some new dependencies, and now it's not passing, it may sometimes be the case that this is equivalent to reviewing the delta in imported code (which, for repos using cargo vendor, is right there in the patch). However it's not always the case.

So fundamentally I don't think the tool should concern itself with the previous state of your repo. The idea that each incremental check-in should be green on cargo vet is a property of the workflow, not the tool.

> I guess one detail is whether it's a useful notion to distinguish between "this is a repo that vet happens to successfully run on" and "this is a repo that has been explicitly vetted and the result checked in". I think that distinction is partially captured by just using `--locked` in CI..?

Yeah. The basic idea is that your linter and CI would enforce that `cargo vet --locked` passes. Preserving that property across the changeset is the job of the engineer.

**Comment by bholley** [comment]
This file seems to be gone now.
