### ISSUE TITLE
Implement the two kinds of "suggest"

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#22]
Writing this out because it's too complicated to fit all in my head at once. There are two suggests:

* Real Suggest
* Vet Suggest

For both commands you are conceptually trying to find the **smallest possible audit you could perform that would properly connect up the graph**. This is vague/complicated, so let's define some concepts/terms.

# Methodology / Terminology

Your audit graph is conceptually a DAG (forest), with nodes containing version numbers and edges containing deltas. This DAG has minimum values and **one** maximum value.

The minimum values are:

* 0.0.0
* full audits
* entries in unaudited (may be multiple for one crate)

The maximum value is the current versions in the Cargo.lock (there may be multiple versions of one crate, but we redo the whole algorithm for each version, so we can ignore that... kinda). 

A path from either direction conceptually starts with all criteria, and then has its criteria intersected by the edge's criteria. 

The goal of the vet resolver is to find every path between the minimums and the maximum. This can be done in either direction -- currently we search from the maximums because there are fewer of them and we can conceptually terminate searches must faster (I think we don't realize this right now, to do so we would need to compare the currently evaluated criteria against validated_criteria and discard that work item if it's a subset, since it can't possibly add more information; right now we only discard paths when the intersection becomes the empty set).

The resolver can fail for two conceptually distinct reasons (although it doesn't distinguish them):

1. There exist **no** paths between the minimums and the maximum
2. Although there exists paths, none of them have sufficient criteria, not even their union

The first is easier to think about, so let's start with that. The graph is disconnected, but conceptually we have some set of paths reaching down and some set paths reaching up. In my head this is like two hands outstretched towards eachother. In a simplified model where there is only one criteria, the solution we're interested in is just `delta(max(min_graph), min(max_graph))`. That is, the smallest distance between the two outstreched hands' fingers.

The second is harder to think about, and I'm not sure how to properly detect/communicate what edges could be cheaply added to make the graph connected from the perspective of Sufficient Criteria. This is especially brain-melty to think about if you want to try to do a Really Amazing Job and actually take path unioning into account.

Ok now with this established, let's see what these two commands are actually asking.

# Vet Suggest

This is to help you get 'vet' passing. Everything described above is exactly the case. Usually the answer will just be "you need a delta from the maximum to the last audit you did".

# Real Suggest

This is to help you clean out your unaudited backlog. This is the same as vet suggest **except all the minimums from unaudited entries have been removed**. Assuming you run this command when vet is passing, the answer will usually just be "you need a full audit for the exact version of the unaudited entry we just removed".

# Implementation strategies

## Quick And Dirty

Assume the "usual" case is good enough, and just recommend exactly that.

Real Suggest would just say "make a full audit for that version", which would always be sufficient but potentially overkill if you actually have a decent audit-chain near the unaudited version and can actually just add a small delta. 

Vet Suggest would say "make a delta from the largest known version mentioned by an audit that is still <= the current version". This could actually be insufficient if done naively enough, because it might be that this is a random floating delta we got from a foreign auditfile without the context of someone they import. In this cast connecting up to that delta might still result in failure.

## Compute The Fingers

Actually run the algorithm forwards and backwards and compare the minimums and maximums. If criteria are uniform (no unioning shenanigans), then this will get you some pretty good results that are hard to complain about. Unfortunately this may still miss some extremely galaxy brain optimal solutions involving doing two small deltas to bridge a floating delta (I don't think anyone can reasonably expect us to find and explain that, right?)

Unfortunately this wouldn't help with situations where a review needs to be made "stricter" or weird situations where you can fix some minor path and make the unioning work out. Maybe that's Too Weird and fine to miss?

## ??? Magic ???

Somehow figure out how to detect and express places where making a review more strict could fix things. I genuinely can't imagine what kind of algorithm this would be right now.

## Ascend Beyond

Get *really* smart about cargo's dependency resolution and start pointing out places where you could upgrade **or downgrade** specific packages to repair the delta graph. I am getting a headache just thinking about this.

**Comment by Gankra** [comment]
For hopefully obvious reasons I am inclined to just ship "Quick And Dirty" for the MVP, with the intent to move to "Compute The Fingers" if we need/want something better.

**Comment by bholley** [comment]
> Your audit graph is conceptually a DAG (forest), with nodes containing version numbers and edges containing deltas. This DAG has minimum values and **one** maximum value.
> 
> The minimum values are:
> 
>     * 0.0.0
> 
>     * full audits
> 
>     * entries in unaudited (may be multiple for one crate)
> 
> 
> The maximum value is the current versions in the Cargo.lock (there may be multiple versions of one crate, but we redo the whole algorithm for each version, so we can ignore that... kinda).

I think "maximum"/"minimum" are sub-optimal names because there might be full audits with a higher version number than the current version in Cargo.lock, in which case you might decide to review a diff from a newer to an older version. Aside from that I agree with the above framing.

> A path from either direction conceptually starts with all criteria, and then has its criteria intersected by the edge's criteria.

I don't think this is quite right. You start with the criteria of the starting node, which is "all criteria" for the first and third case but not for the second case (full audits).

> The goal of the vet resolver is to find every path between the minimums and the maximum.

Yes.

> This can be done in either direction -- currently we search from the maximums because there are fewer of them

Strictly speaking there will always be exactly one maximum per search, right?


> The first is easier to think about, so let's start with that. The graph is disconnected, but conceptually we have some set of paths reaching down and some set paths reaching up. In my head this is like two hands outstretched towards eachother. In a simplified model where there is only one criteria, the solution we're interested in is just `delta(max(min_graph), min(max_graph))`. That is, the smallest distance between the two outstreched hands' fingers.

I think it's incorrect to model the distance in version-number space. In a world where I've got full audits for 1.2 and 1.3, and I'm we're trying to suggest how to audit 1.2.5, you can't tell which direction is easier without measuring the size of both diffs.

Obviously it's expensive to do diffs, so we'll want to cache those (immutable) results somewhere persistent (~/.cargo-vet/cache or somesuch).

> The second is harder to think about, and I'm not sure how to properly detect/communicate what edges could be cheaply added to make the graph connected from the perspective of Sufficient Criteria. This is especially brain-melty to think about if you want to try to do a Really Amazing Job and actually take path unioning into account.

I think these two cases can be handled uniformly, see below.
 
> Ok now with this established, let's see what these two commands are actually asking.
> # Vet Suggest
> 
> This is to help you get 'vet' passing. Everything described above is exactly the case. Usually the answer will just be "you need a delta from the maximum to the last audit you did".

Yes.

> # Real Suggest
> 
> This is to help you clean out your unaudited backlog. This is the same as vet suggest **except all the minimums from unaudited entries have been removed**. Assuming you run this command when vet is passing, the answer will usually just be "you need a full audit for the exact version of the unaudited entry we just removed".

For some definition of "usually". However my hope here is that it's not uncommon in this situation to recommend a delta audit from some foreign audit for a different version to the local version. If you imagine wasmtime bootstrapping with an import from a fully-vetted Firefox, roughly have of the initial suggestions will be delta audits.

> # Implementation strategies
> ## Quick And Dirty
> 
> Assume the "usual" case is good enough, and just recommend exactly that.
> 
> Real Suggest would just say "make a full audit for that version", which would always be sufficient but potentially overkill if you actually have a decent audit-chain near the unaudited version and can actually just add a small delta.

I think this misses too much, per the wasmtime-bootstrapping example above.
 
> Vet Suggest would say "make a delta from the largest known version mentioned by an audit that is still <= the current version". This could actually be insufficient if done naively enough, because it might be that this is a random floating delta we got from a foreign auditfile without the context of someone they import. In this cast connecting up to that delta might still result in failure.

Yes, I think we can do better.

> ## Compute The Fingers
> 
> Actually run the algorithm forwards and backwards and compare the minimums and maximums. If criteria are uniform (no unioning shenanigans), then this will get you some pretty good results that are hard to complain about.

So this might be what you have in mind, but here's a sketch of what I'm picturing for the algorithm.

(1) Determine the required |self| label for this node. Strictly speaking this can be indeterminate in the case where the node's ancestor is also missing audits (because such an audit, when recorded, could change the criteria requirements for its descendants). However, I think it can be reasonably approximated by walking down the ancestor chain from the nearest ancestor with a |policy| entry to the first unaudited node, and using that node's required criteria.

(2) Subtract the current |self| label from the answer in (1) to determine the missing criteria.

(3) Compute all paths from the set of "minimums" that preserve the set from (2), collect the deduplicated endpoints.

(4) Toss out any endpoints that are strictly farther in version space from the goal than another entry (so at most we're left with two: one below and one above the goal). This is technically an approximation but likely good enough.

(5) Measure+Cache the diff size for the endpoint(s) in (4), picking the smaller one if applicable. Report that.


> Unfortunately this may still miss some extremely galaxy brain optimal solutions involving doing two small deltas to bridge a floating delta (I don't think anyone can reasonably expect us to find and explain that, right?)
> 
> Unfortunately this wouldn't help with situations where a review needs to be made "stricter" or weird situations where you can fix some minor path and make the unioning work out. Maybe that's Too Weird and fine to miss?
>
> Get _really_ smart about cargo's dependency resolution and start pointing out places where you could upgrade **or downgrade** specific packages to repair the delta graph. I am getting a headache just thinking about this.

I am fine with passing on these four optimization opportunities for now.

**Comment by Gankra** [comment]
> I think "maximum"/"minimum" are sub-optimal names because there might be full audits with a higher version number than the current version in Cargo.lock, in which case you might decide to review a diff from a newer to an older version. Aside from that I agree with the above framing.

Wait I was joking to myself about "anti-diffs" are those actually real in your model 🙀

> I don't think this is quite right. You start with the criteria of the starting node, which is "all criteria" for the first and third case but not for the second case (full audits).

In my implementation I "lower" a full audit to a delta to 0.0.0, so they end up not being special, but fair.

> I think it's incorrect to model the distance in version-number space. In a world where I've got full audits for 1.2 and 1.3, and I'm we're trying to suggest how to audit 1.2.5, you can't tell which direction is easier without measuring the size of both diffs.

Wow that is terrifying but, I agree that's how you get the Best Answers if you're willing to do it.

> So this might be what you have in mind, but here's a sketch of what I'm picturing for the algorithm.

I don't really understand what you mean by this in step 1:

> However, I think it can be reasonably approximated by walking down the ancestor chain from the nearest ancestor with a |policy| entry to the first unaudited node, and using that node's required criteria.

Could you give an example?

(The rest sounds plausible, need to mull it over)

**Comment by bholley** [comment]
> Wait I was joking to myself about "anti-diffs" are those actually real in your model 🙀

Yes. As an example, Firefox audited foo-1.3, and wasmtime depends on foo-1.2. Likely way easier to review the anti-diff than do a fresh review of 1.2. You might hypothesize that wasmtime should just upgrade to 1.3, but that might not be directly in their power to do (i.e. it might be deep in the dependency tree).

> In my implementation I "lower" a full audit to a delta to 0.0.0, so they end up not being special, but fair.

Ah I see.



> I don't really understand what you mean by this in step 1:
> 
> > However, I think it can be reasonably approximated by walking down the ancestor chain from the nearest ancestor with a |policy| entry to the first unaudited node, and using that node's required criteria.
> 
> Could you give an example?

Sure. Firefox sets default_criteria='secure' and has the following hierarchy:
gkrust (first-party, policy.criteria=secure (either implicitly or explicitly))
--gecko_logging_infrastructure (first-party, policy.criteria=safe_to_run_locally)
----logorama (third-party, unaudited)
------leftpad (third_party, unaudited)

The suggest algorithm is trying to do `leftpad`, and needs to determine what kind of audit criteria to recommend. Strictly speaking, we don't know, because it depends on the `dependency_criteria` for `logorama`, which we don't have yet. However, I propose that we walk up the ancestor tree looking for a first-party crate with policy criteria (in this case gecko_logging_infrastructure) and use its criteria (in this case, `safe_to_run_locally`).

**Comment by bholley** [comment]
Actually, I think that's not quite right. We want to find the nearest first-party crate with a policy entry, and then potentially walk further down the chain from there across any fully-audited third-party crates.

**Comment by Gankra** [comment]
I can kinda see what you're gesturing at but there's a tingling in the back of my mind that things are too messy in general. I'll ponder it.
